import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'HI';

export interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Brand & Header
    'brand.name': 'KUSHAL',
    'brand.subtitle': 'National Labour Market Intelligence',
    'header.search': 'Search...',
    'header.searchShortcut': 'Ctrl+K',
    'header.scope': 'Scope',
    'header.scopeAllIndia': 'All India',
    'header.notifications': 'Early Warning Alerts',
    'header.toggleLang': 'Switch Language',
    'header.signOut': 'Sign Out',
    'header.officer': 'Officer',
    'header.govSignIn': 'Government Sign In',
    'header.backOverview': 'Back to Overview',

    // Navigation
    'nav.sectionGov': 'GOVERNMENT',
    'nav.sectionPublic': 'PUBLIC',
    'nav.overview': 'Overview',
    'nav.labourMarket': 'Labour Market',
    'nav.forecasts': 'Forecasts',
    'nav.earlyWarnings': 'Early Warnings',
    'nav.skillTransitions': 'Skill Transitions',
    'nav.trainingAllocation': 'Training Allocation',
    'nav.skillFinder': 'Skill Finder',
    'nav.myRoadmap': 'My Roadmap',
    'nav.exit': 'Exit',

    // Landing Page
    'landing.eyebrow': 'NATIONAL LABOUR MARKET INTELLIGENCE',
    'landing.heroTitle1': "Understand India's",
    'landing.heroTitle2': 'changing workforce.',
    'landing.heroSubtitle': 'Identify skill shortages, anticipate emerging demand, and plan training priorities across India.',
    'landing.heroCta': 'Government Sign In',
    'landing.ministry': 'Ministry of Skill Development & Entrepreneurship (MSDE)',
    'landing.sihTag': 'SIH 2026 · Problem Statement 26246',
    'landing.glanceTitle': 'India at a glance',
    'landing.glanceSource': 'Source: MoSPI — PLFS 2025',
    'landing.lfpr': 'Labour Force Participation',
    'landing.wpr': 'Worker Population Ratio',
    'landing.ur': 'Unemployment Rate',
    'landing.agriShare': 'Employment in Agriculture',
    'landing.usualStatus': 'Usual status (15+ years)',
    'landing.sectorShare': 'National sector share',
    'landing.workflowEyebrow': 'IDENTIFY → FORECAST → PLAN',
    'landing.workflowTitle': 'From labour-market signals to actionable workforce planning.',
    'landing.step1Title': '01 / Identify',
    'landing.step1Desc': 'Detect skill shortages and emerging demand across regional industry clusters using employer requisitions and NCO 2015 standards.',
    'landing.step2Title': '02 / Forecast',
    'landing.step2Desc': 'Anticipate future labour-market gaps across 3, 6, and 12-month horizons by joining macro PLFS baselines with hiring growth velocity.',
    'landing.step3Title': '03 / Plan',
    'landing.step3Desc': 'Prioritize ITI seat capacity, accredited training sanctioning, and local skill development programs based on effective supply gaps.',
    'landing.footer': 'National Labour Market Intelligence Decision Support Platform',

    // Sign In Page
    'signin.title': 'Government Sign In',
    'signin.subtitle': 'Authorized government officers and planning authorities',
    'signin.emailLabel': 'Email / Government ID',
    'signin.passwordLabel': 'Password',
    'signin.forgotPassword': 'Forgot Password?',
    'signin.submit': 'Sign In to All India Dashboard',
    'signin.restricted': 'Authorized government users only.',
    'signin.footerNote': 'Decision Support System · SIH 2026 PS 26246',
    'signin.errorEmpty': 'Please enter a valid government email or ID',

    // Overview Page
    'overview.title': 'National Labour Market Overview',
    'overview.subtitle': 'Real-time demand-supply synthesis across 36 States & UTs with DataMeet boundary intelligence.',
    'overview.kpiDemand': 'Active Labour Demand',
    'overview.kpiDemandSub': 'Unique job requisitions across sectors',
    'overview.kpiShortage': 'Critical Skill Shortages',
    'overview.kpiShortageSub': 'Skills with demand exceeding supply >2.0x',
    'overview.kpiTraining': 'Training Infrastructure',
    'overview.kpiTrainingSub': 'Active accredited training centres',
    'overview.kpiBalance': 'Labour Balance Index',
    'overview.kpiBalanceSub': 'Ratio of balanced to stressed skill nodes',
    'overview.mapTitle': 'Geographic Labour Market Map',
    'overview.topSkillsTitle': 'Top In-Demand Technical Skills',
    'overview.colSkill': 'Skill Name',
    'overview.colSector': 'Dominant Sector',
    'overview.colDemandIndex': 'Demand Index',
    'overview.colSupply': 'Effective Supply',
    'overview.colGap': 'Gap Status',
    'overview.colAction': 'Action',
    'overview.viewDetail': 'View Detail',

    // Labour Market Page
    'labour.title': 'Labour Market Intelligence',
    'labour.subtitle': 'Comprehensive multi-source labour market analysis across geographic clusters and industry sectors.',
    'labour.filterState': 'State / UT',
    'labour.filterDistrict': 'District',
    'labour.filterSector': 'Industry Sector',
    'labour.filterHorizon': 'Time Horizon',
    'labour.allStates': 'All States & UTs',
    'labour.allDistricts': 'All Districts',
    'labour.allSectors': 'All Sectors',
    'labour.horizon3m': '3 Months',
    'labour.horizon6m': '6 Months',
    'labour.horizon12m': '12 Months',
    'labour.resetFilters': 'Reset Filters',
    'labour.profileTitle': 'State Economic & Labour Profile',
    'labour.primaryIndustries': 'Primary Industries',
    'labour.labourClusters': 'Key Labour Clusters',
    'labour.sectorDemandTitle': 'Sectoral Labour Demand & Growth',
    'labour.skillGapsTitle': 'Skill Supply vs. Demand Gap Matrix',
    'labour.jobEvidenceTitle': 'Synthetic Job Evidence & Employer Postings',
    'labour.colOccupation': 'Occupation (NCO 2015)',
    'labour.colPostings': 'Postings',
    'labour.colVelocity': 'Hiring Velocity',
    'labour.colEmployers': 'Active Employers',
    'labour.colDemandLevel': 'Demand Level',
    'labour.colSupplyLevel': 'Supply Level',
    'labour.colNetGap': 'Net Gap',
    'labour.colJobTitle': 'Job Requisition',
    'labour.colCompany': 'Employer (Synthetic)',
    'labour.colLocation': 'Location',
    'labour.colRequiredSkills': 'Key Skills',
    'labour.colDate': 'Posted Date',

    // Forecasts Page
    'forecast.title': 'Labour Demand & Skill Forecasting',
    'forecast.subtitle': 'Predictive models for 3, 6, and 12-month hiring trajectories based on leading indicators and macro PLFS trends.',
    'forecast.badgeModeled': 'MODELED',
    'forecast.badgeForecast': 'FORECAST',
    'forecast.horizonTitle': 'Forecast Horizon',
    'forecast.q1': '3 Months (Near-term)',
    'forecast.h1': '6 Months (Mid-term)',
    'forecast.fy': '12 Months (Full Year)',
    'forecast.growthTrajectory': 'Projected Demand Trajectory',
    'forecast.confidenceLevel': 'Confidence Interval: 85% — 92%',
    'forecast.emergingSkillsTitle': 'High-Growth Emerging Skills Forecast',
    'forecast.decliningSkillsTitle': 'Declining / Saturated Skills',
    'forecast.projectedGrowth': 'Projected Growth',
    'forecast.riskLevel': 'Risk Level',

    // Early Warnings Page
    'warnings.title': 'Early Warning Alerts',
    'warnings.subtitle': 'Automated detection of structural labour imbalances, sudden supply drops, and emerging skill deficits.',
    'warnings.filterSeverity': 'Filter Severity',
    'warnings.allSeverities': 'All Alerts',
    'warnings.sevHigh': 'High Severity',
    'warnings.sevMedium': 'Medium Severity',
    'warnings.sevLow': 'Low Severity',
    'warnings.interventionTitle': 'Recommended Policy Intervention',
    'warnings.triggerDate': 'Detected',
    'warnings.affectedGeography': 'Affected Geography',
    'warnings.rootCause': 'Root Signal Cause',
    'warnings.takeAction': 'Initiate Allocation Plan',

    // Skill Transitions Page
    'transitions.title': 'Skill Graph & Transition Pathways',
    'transitions.subtitle': 'Map competency adjacencies to navigate from surplus or declining occupations to high-growth target roles.',
    'transitions.fromSkill': 'Current / Surplus Skill',
    'transitions.bridgeCompetency': 'Bridge Competency',
    'transitions.targetOccupation': 'Target Occupation',
    'transitions.trainingProgram': 'Recommended Training',
    'transitions.feasibility': 'Transition Feasibility',
    'transitions.highFeasibility': 'High Feasibility (>80% overlap)',
    'transitions.midFeasibility': 'Moderate Feasibility (50-80%)',
    'transitions.explorePath': 'Explore Pathway',

    // Training Allocation Page
    'training.title': 'Training Allocation & Capacity Planning',
    'training.subtitle': 'Data-driven seat allocation recommendations for ITIs and training centres based on calculated effective supply gaps.',
    'training.stateFilter': 'State Filter',
    'training.allStates': 'All States & UTs',
    'training.competencySector': 'Skill Competency Sector',
    'training.allCompetencies': 'All Competencies',
    'training.budgetScenario': 'Budget Scenario',
    'training.budgetConstrained': 'Constrained (-20%)',
    'training.budgetBaseline': 'Baseline Budget (1.0x)',
    'training.budgetExpansion': 'Expansion (+30%)',
    'training.currentSupply': 'Current Effective Supply',
    'training.recommendedCap': 'Recommended Sanctioned Capacity',
    'training.netChange': 'Net Capacity Change',
    'training.seats': 'seats',
    'training.gapCalcTitle': 'Skill Gap Calculations',
    'training.gapCalcSub': 'Derived: Demand Units - Effective Supply Units = Gap Units',
    'training.colState': 'State / Geography',
    'training.colSkill': 'Skill',
    'training.colRelatedSector': 'Related Sector',
    'training.colDemandUnits': 'Demand Units',
    'training.colSupplyUnits': 'Effective Supply',
    'training.colGapUnits': 'Gap Units',
    'training.colMarketStatus': 'Market Status',
    'training.noRecords': 'No skill gap records available for selected geography.',
    'training.recsTitle': 'Training Capacity Recommendations',
    'training.colCentre': 'Centre & Location',
    'training.colCourse': 'Course & Skill',
    'training.colCurrentSeats': 'Current Seats',
    'training.colRecSeats': 'Recommended',
    'training.colDiff': 'Change',
    'training.colImpact': 'Estimated Impact',
    'training.loading': 'Calculating training capacity allocation...',

    // Public Skill Finder Page
    'finder.title': 'Skill Finder',
    'finder.subtitle': 'Explore high-demand skills and career pathways in your district.',
    'finder.profileTitle': '1. Your Profile',
    'finder.state': 'State',
    'finder.district': 'District',
    'finder.allStates': 'All States',
    'finder.allDistricts': 'All Districts',
    'finder.primarySkill': 'Your Primary Skill / Trade',
    'finder.educationLevel': 'Education Level',
    'finder.edu10th': '10th Standard',
    'finder.edu12th': '12th Standard',
    'finder.eduIti': 'ITI / Polytechnic Diploma',
    'finder.eduGraduate': 'Graduate',
    'finder.opportunitiesIn': '2. Opportunities in',
    'finder.inIndia': 'India',
    'finder.highDemandTitle': 'High-Demand Skills',
    'finder.shortageTitle': 'Shortage & Emerging Skills',
    'finder.demandLabel': 'Demand:',
    'finder.criticalShortage': 'Critical Shortage',
    'finder.emergingSkill': 'Emerging Skill',
    'finder.shortage': 'Shortage',
    'finder.roadmapBannerTitle': 'Generate your personalized learning roadmap',
    'finder.roadmapBannerDesc': 'See step-by-step bridge skills from {skill} to target shortage occupations.',
    'finder.viewRoadmap': 'View My Roadmap',

    // My Roadmap Page
    'roadmap.back': 'Back to Skill Finder',
    'roadmap.title': 'My Learning Roadmap',
    'roadmap.subtitle': 'Path from {skill} to target shortage occupation',
    'roadmap.step1Title': 'Current Skill Baseline',
    'roadmap.step1Desc': 'Demonstrated competency in {skill}. (Education: {education})',
    'roadmap.step1Status': 'Current',
    'roadmap.step2Title': 'Identified Skill Gap',
    'roadmap.step2Desc': 'Missing industrial controller & PLC ladder logic modules required for Level 5 automation roles.',
    'roadmap.step2Status': 'Gap',
    'roadmap.step3Title': 'Recommended Bridge Skill',
    'roadmap.step3Desc': 'PLC Programming & Industrial Telemetry (6 Weeks / 180 Hours structured training).',
    'roadmap.step3Status': 'Bridge',
    'roadmap.step4Title': 'Target Qualification Goal',
    'roadmap.step4Desc': 'Industrial Automation Technician (NCO 2015 Code: 3115.0100 · High industry shortage).',
    'roadmap.step4Status': 'Target',
    'roadmap.trainingCentresTitle': 'Training Centres Offering This Bridge Program',
    'roadmap.trainingCentresDesc': 'Accredited Government and Aided ITIs offering subsidized bridge courses under PMKVY and State Skill Mission schemes.',
    'roadmap.searchAnother': 'Search Another Skill',

    // Search Modal
    'search.placeholder': 'Search NCO codes (e.g. 1111.0100), skills, occupations, districts...',
    'search.quickTitle': 'Quick Search across Canonical Datasets',
    'search.quickSub': 'Type an NCO 2015 code, trade title, skill keyword, or district name',
    'search.noResults': 'No matching occupations, skills, or districts found for "{query}".',
    'search.occupations': 'Occupations (NCO 2015)',
    'search.skills': 'Skills',
    'search.districts': 'Geographic Districts',
    'search.sectors': 'Sectors',
    'search.filterDashboard': 'Filter Dashboard',
    'search.filterSector': 'Filter Sector',

    // Map & Geography
    'map.title': 'All India Labour Market Map',
    'map.instruction': 'Click any state on the map to drill down into district-level intelligence.',
    'map.resetAllIndia': 'Reset to All India',
    'map.loadingStates': 'Loading India spatial boundaries...',
    'map.loadingDistricts': 'Loading district boundaries...',
    'map.legendTitle': 'Labour Market Status',
    'map.statusCriticalShortage': 'Critical Shortage',
    'map.statusShortage': 'Shortage',
    'map.statusBalanced': 'Balanced',
    'map.statusOversupply': 'Oversupply',
    'map.statusCriticalOversupply': 'Critical Oversupply',
    'map.statusInsufficient': 'Insufficient Data',
    'map.demandLevel': 'Demand Level',
    'map.criticalShortages': 'Critical Shortages',
    'map.totalPostings': 'Total Postings',
    'map.activeEmployers': 'Active Employers',
    'map.topShortage': 'Top Shortage',
    'map.clickExplore': 'Click to explore state details',
    'map.attribution': 'Geographic boundaries: DataMeet India spatial repository',

    // Common & Badges
    'common.source': 'Source',
    'common.data': 'Data',
    'common.provenance': 'Provenance',
    'common.refOfficial': 'OFFICIAL REFERENCE',
    'common.syntheticDev': 'SYNTHETIC / DEVELOPMENT',
    'common.modeledForecast': 'MODELED / FORECAST',
    'common.observed': 'OBSERVED',
    'common.loading': 'Loading labour intelligence...',
    'common.noData': 'No records found matching the current filters.',
    'common.close': 'Close',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.balanced': 'Balanced',
    'common.shortage': 'Shortage',
    'common.oversupply': 'Oversupply'
  },
  HI: {
    // Brand & Header
    'brand.name': 'KUSHAL',
    'brand.subtitle': 'राष्ट्रीय श्रम बाज़ार आसूचना',
    'header.search': 'खोजें...',
    'header.searchShortcut': 'Ctrl+K',
    'header.scope': 'कार्यक्षेत्र',
    'header.scopeAllIndia': 'अखिल भारतीय',
    'header.notifications': 'प्रारंभिक चेतावनी अलर्ट',
    'header.toggleLang': 'भाषा बदलें',
    'header.signOut': 'साइन आउट',
    'header.officer': 'अधिकारी',
    'header.govSignIn': 'सरकारी साइन इन',
    'header.backOverview': 'सिंहावलोकन पर वापस जाएं',

    // Navigation
    'nav.sectionGov': 'सरकारी प्रशासन',
    'nav.sectionPublic': 'सार्वजनिक नागरिक सेवा',
    'nav.overview': 'सिंहावलोकन',
    'nav.labourMarket': 'श्रम बाज़ार',
    'nav.forecasts': 'पूर्वानुमान',
    'nav.earlyWarnings': 'प्रारंभिक चेतावनी',
    'nav.skillTransitions': 'कौशल परिवर्तन',
    'nav.trainingAllocation': 'प्रशिक्षण आवंटन',
    'nav.skillFinder': 'कौशल खोजक',
    'nav.myRoadmap': 'मेरा रोडमैप',
    'nav.exit': 'बाहर निकलें',

    // Landing Page
    'landing.eyebrow': 'राष्ट्रीय श्रम बाज़ार आसूचना',
    'landing.heroTitle1': 'भारत के परिवर्तनशील',
    'landing.heroTitle2': 'कार्यबल को समझें।',
    'landing.heroSubtitle': 'कौशल की कमी की पहचान करें, उभरती मांग का पूर्वानुमान लगाएं, और पूरे भारत में प्रशिक्षण प्राथमिकताओं की योजना बनाएं।',
    'landing.heroCta': 'सरकारी साइन इन',
    'landing.ministry': 'कौशल विकास एवं उद्यमशीलता मंत्रालय (MSDE)',
    'landing.sihTag': 'SIH 2026 · समस्या विवरण 26246',
    'landing.glanceTitle': 'एक नज़र में भारत',
    'landing.glanceSource': 'स्रोत: सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय — PLFS 2025',
    'landing.lfpr': 'श्रम बल भागीदारी दर (LFPR)',
    'landing.wpr': 'श्रमिक जनसंख्या अनुपात (WPR)',
    'landing.ur': 'बेरोज़गारी दर',
    'landing.agriShare': 'कृषि में रोज़गार हिस्सेदारी',
    'landing.usualStatus': 'सामान्य स्थिति (15+ वर्ष)',
    'landing.sectorShare': 'राष्ट्रीय क्षेत्र हिस्सेदारी',
    'landing.workflowEyebrow': 'पहचानें → पूर्वानुमान करें → योजना बनाएं',
    'landing.workflowTitle': 'श्रम बाज़ार के संकेतों से व्यावहारिक कार्यबल योजना तक।',
    'landing.step1Title': '01 / पहचानें',
    'landing.step1Desc': 'नियोक्ता मांग और NCO 2015 मानकों का उपयोग करके क्षेत्रीय उद्योग समूहों में कौशल की कमी और उभरती मांग का पता लगाएं।',
    'landing.step2Title': '02 / पूर्वानुमान',
    'landing.step2Desc': 'भर्ती वृद्धि दर के साथ मैक्रो PLFS आधार रेखाओं को जोड़कर 3, 6 और 12 महीने के क्षितिजों में भविष्य के श्रम-बाज़ार अंतरालों का अनुमान लगाएं।',
    'landing.step3Title': '03 / योजना',
    'landing.step3Desc': 'प्रभावी आपूर्ति अंतराल के आधार पर ITI सीट क्षमता, मान्यता प्राप्त प्रशिक्षण स्वीकृति और स्थानीय कौशल विकास कार्यक्रमों को प्राथमिकता दें।',
    'landing.footer': 'राष्ट्रीय श्रम बाज़ार आसूचना निर्णय समर्थन मंच',

    // Sign In Page
    'signin.title': 'सरकारी साइन इन',
    'signin.subtitle': 'अधिकृत सरकारी अधिकारी एवं योजना प्राधिकरण',
    'signin.emailLabel': 'ईमेल / सरकारी पहचान पत्र (ID)',
    'signin.passwordLabel': 'पासवर्ड',
    'signin.forgotPassword': 'पासवर्ड भूल गए?',
    'signin.submit': 'अखिल भारतीय डैशबोर्ड में साइन इन करें',
    'signin.restricted': 'केवल अधिकृत सरकारी उपयोगकर्ताओं के लिए।',
    'signin.footerNote': 'निर्णय समर्थन प्रणाली · SIH 2026 PS 26246',
    'signin.errorEmpty': 'कृपया वैध सरकारी ईमेल या पहचान दर्ज करें',

    // Overview Page
    'overview.title': 'राष्ट्रीय श्रम बाज़ार सिंहावलोकन',
    'overview.subtitle': 'DataMeet सीमा आसूचना के साथ 36 राज्यों और केंद्र शासित प्रदेशों में वास्तविक मांग-आपूर्ति संश्लेषण।',
    'overview.kpiDemand': 'सक्रिय श्रम मांग',
    'overview.kpiDemandSub': 'विभिन्न क्षेत्रों में अनूठी नौकरी मांग',
    'overview.kpiShortage': 'गंभीर कौशल कमियां',
    'overview.kpiShortageSub': 'मांग >2.0x आपूर्ति वाले प्रमुख कौशल',
    'overview.kpiTraining': 'प्रशिक्षण अवसंरचना',
    'overview.kpiTrainingSub': 'सक्रिय मान्यता प्राप्त प्रशिक्षण केंद्र',
    'overview.kpiBalance': 'श्रम संतुलन सूचकांक',
    'overview.kpiBalanceSub': 'संतुलित से तनावग्रस्त कौशल नोड्स का अनुपात',
    'overview.mapTitle': 'भौगोलिक श्रम बाज़ार मानचित्र',
    'overview.topSkillsTitle': 'शीर्ष मांग वाले तकनीकी कौशल',
    'overview.colSkill': 'कौशल का नाम',
    'overview.colSector': 'प्रमुख क्षेत्र',
    'overview.colDemandIndex': 'मांग सूचकांक',
    'overview.colSupply': 'प्रभावी आपूर्ति',
    'overview.colGap': 'अंतराल स्थिति',
    'overview.colAction': 'कार्रवाई',
    'overview.viewDetail': 'विवरण देखें',

    // Labour Market Page
    'labour.title': 'श्रम बाज़ार आसूचना',
    'labour.subtitle': 'भौगोलिक समूहों और उद्योग क्षेत्रों में व्यापक बहु-स्रोत श्रम बाज़ार विश्लेषण।',
    'labour.filterState': 'राज्य / केंद्र शासित प्रदेश',
    'labour.filterDistrict': 'ज़िला',
    'labour.filterSector': 'उद्योग क्षेत्र',
    'labour.filterHorizon': 'समय सीमा',
    'labour.allStates': 'सभी राज्य एवं केंद्र शासित प्रदेश',
    'labour.allDistricts': 'सभी ज़िले',
    'labour.allSectors': 'सभी क्षेत्र',
    'labour.horizon3m': '3 महीने',
    'labour.horizon6m': '6 महीने',
    'labour.horizon12m': '12 महीने',
    'labour.resetFilters': 'फ़िल्टर रीसेट करें',
    'labour.profileTitle': 'राज्य आर्थिक एवं श्रम प्रोफ़ाइल',
    'labour.primaryIndustries': 'प्राथमिक उद्योग',
    'labour.labourClusters': 'प्रमुख श्रम क्लस्टर',
    'labour.sectorDemandTitle': 'क्षेत्रीय श्रम मांग एवं वृद्धि',
    'labour.skillGapsTitle': 'कौशल आपूर्ति बनाम मांग अंतराल मैट्रिक्स',
    'labour.jobEvidenceTitle': 'सिंथेटिक नौकरी साक्ष्य एवं नियोक्ता विज्ञापन',
    'labour.colOccupation': 'व्यवसाय (NCO 2015)',
    'labour.colPostings': 'विज्ञापन संख्या',
    'labour.colVelocity': 'भर्ती गति',
    'labour.colEmployers': 'सक्रिय नियोक्ता',
    'labour.colDemandLevel': 'मांग स्तर',
    'labour.colSupplyLevel': 'आपूर्ति स्तर',
    'labour.colNetGap': 'शुद्ध अंतराल',
    'labour.colJobTitle': 'नौकरी पद',
    'labour.colCompany': 'नियोक्ता (सिंथेटिक)',
    'labour.colLocation': 'स्थान',
    'labour.colRequiredSkills': 'आवश्यक कौशल',
    'labour.colDate': 'विज्ञापन तिथि',

    // Forecasts Page
    'forecast.title': 'श्रम मांग एवं कौशल पूर्वानुमान',
    'forecast.subtitle': 'अग्रणी संकेतकों और मैक्रो PLFS प्रवृत्तियों के आधार पर 3, 6 और 12 महीने के भर्ती प्रक्षेपवक्र का भविष्य कहनेवाला मॉडल।',
    'forecast.badgeModeled': 'मॉडल किया गया',
    'forecast.badgeForecast': 'पूर्वानुमान',
    'forecast.horizonTitle': 'पूर्वानुमान समय सीमा',
    'forecast.q1': '3 महीने (निकट अवधि)',
    'forecast.h1': '6 महीने (मध्यम अवधि)',
    'forecast.fy': '12 महीने (पूरा वर्ष)',
    'forecast.growthTrajectory': 'अनुमानित मांग प्रक्षेपवक्र',
    'forecast.confidenceLevel': 'विश्वास अंतराल: 85% — 92%',
    'forecast.emergingSkillsTitle': 'उच्च-वृद्धि वाले उभरते कौशल पूर्वानुमान',
    'forecast.decliningSkillsTitle': 'घटते / संतृप्त कौशल',
    'forecast.projectedGrowth': 'अनुमानित वृद्धि',
    'forecast.riskLevel': 'जोखिम स्तर',

    // Early Warnings Page
    'warnings.title': 'प्रारंभिक चेतावनी अलर्ट',
    'warnings.subtitle': 'संरचनात्मक श्रम असंतुलन, अचानक आपूर्ति गिरावट और उभरते कौशल घाटे का स्वचालित पता लगाना।',
    'warnings.filterSeverity': 'गंभीरता फ़िल्टर',
    'warnings.allSeverities': 'सभी अलर्ट',
    'warnings.sevHigh': 'उच्च गंभीरता',
    'warnings.sevMedium': 'मध्यम गंभीरता',
    'warnings.sevLow': 'निम्न गंभीरता',
    'warnings.interventionTitle': 'अनुशंसित नीति हस्तक्षेप',
    'warnings.triggerDate': 'पहचान तिथि',
    'warnings.affectedGeography': 'प्रभावित भूगोल',
    'warnings.rootCause': 'मूल कारण संकेत',
    'warnings.takeAction': 'आवंटन योजना प्रारंभ करें',

    // Skill Transitions Page
    'transitions.title': 'कौशल ग्राफ़ एवं परिवर्तन मार्ग',
    'transitions.subtitle': 'अधिशेष या घटते व्यवसायों से उच्च-विकास वाले लक्षित पदों पर जाने के लिए योग्यता निकटता का मानचित्रण करें।',
    'transitions.fromSkill': 'वर्तमान / अधिशेष कौशल',
    'transitions.bridgeCompetency': 'ब्रिज योग्यता',
    'transitions.targetOccupation': 'लक्षित व्यवसाय',
    'transitions.trainingProgram': 'अनुशंसित प्रशिक्षण',
    'transitions.feasibility': 'परिवर्तन व्यवहार्यता',
    'transitions.highFeasibility': 'उच्च व्यवहार्यता (>80% समानता)',
    'transitions.midFeasibility': 'मध्यम व्यवहार्यता (50-80%)',
    'transitions.explorePath': 'मार्ग देखें',

    // Training Allocation Page
    'training.title': 'प्रशिक्षण आवंटन एवं क्षमता योजना',
    'training.subtitle': 'गणना किए गए प्रभावी आपूर्ति अंतराल के आधार पर ITIs और प्रशिक्षण केंद्रों के लिए डेटा-संचालित सीट आवंटन सिफारिशें।',
    'training.stateFilter': 'राज्य फ़िल्टर',
    'training.allStates': 'सभी राज्य एवं केंद्र शासित प्रदेश',
    'training.competencySector': 'कौशल योग्यता क्षेत्र',
    'training.allCompetencies': 'सभी योग्यताएं',
    'training.budgetScenario': 'बजट परिदृश्य',
    'training.budgetConstrained': 'सीमित (-20%)',
    'training.budgetBaseline': 'आधारभूत बजट (1.0x)',
    'training.budgetExpansion': 'विस्तार (+30%)',
    'training.currentSupply': 'वर्तमान प्रभावी आपूर्ति',
    'training.recommendedCap': 'अनुशंसित स्वीकृत क्षमता',
    'training.netChange': 'शुद्ध क्षमता परिवर्तन',
    'training.seats': 'सीटें',
    'training.gapCalcTitle': 'कौशल अंतराल गणना',
    'training.gapCalcSub': 'व्युत्पन्न: मांग इकाइयां - प्रभावी आपूर्ति इकाइयां = अंतराल इकाइयां',
    'training.colState': 'राज्य / भूगोल',
    'training.colSkill': 'कौशल',
    'training.colRelatedSector': 'संबंधित क्षेत्र',
    'training.colDemandUnits': 'मांग इकाइयां',
    'training.colSupplyUnits': 'प्रभावी आपूर्ति',
    'training.colGapUnits': 'अंतराल इकाइयां',
    'training.colMarketStatus': 'बाज़ार स्थिति',
    'training.noRecords': 'चयनित भूगोल के लिए कोई कौशल अंतराल रिकॉर्ड उपलब्ध नहीं है।',
    'training.recsTitle': 'प्रशिक्षण क्षमता सिफारिशें',
    'training.colCentre': 'केंद्र एवं स्थान',
    'training.colCourse': 'पाठ्यक्रम एवं कौशल',
    'training.colCurrentSeats': 'वर्तमान सीटें',
    'training.colRecSeats': 'अनुशंसित',
    'training.colDiff': 'परिवर्तन',
    'training.colImpact': 'अनुमानित प्रभाव',
    'training.loading': 'प्रशिक्षण क्षमता आवंटन की गणना की जा रही है...',

    // Public Skill Finder Page
    'finder.title': 'कौशल खोजक',
    'finder.subtitle': 'अपने ज़िले में उच्च मांग वाले कौशल और करियर मार्गों का अन्वेषण करें।',
    'finder.profileTitle': '1. आपकी प्रोफ़ाइल',
    'finder.state': 'राज्य',
    'finder.district': 'ज़िला',
    'finder.allStates': 'सभी राज्य',
    'finder.allDistricts': 'सभी ज़िले',
    'finder.primarySkill': 'आपका प्राथमिक कौशल / व्यवसाय',
    'finder.educationLevel': 'शिक्षा का स्तर',
    'finder.edu10th': '10वीं पास',
    'finder.edu12th': '12वीं पास',
    'finder.eduIti': 'ITI / पॉलिटेक्निक डिप्लोमा',
    'finder.eduGraduate': 'स्नातक',
    'finder.opportunitiesIn': '2. अवसर स्थान:',
    'finder.inIndia': 'भारत',
    'finder.highDemandTitle': 'उच्च मांग वाले कौशल',
    'finder.shortageTitle': 'कमी एवं उभरते कौशल',
    'finder.demandLabel': 'मांग:',
    'finder.criticalShortage': 'गंभीर कमी',
    'finder.emergingSkill': 'उभरता कौशल',
    'finder.shortage': 'कमी',
    'finder.roadmapBannerTitle': 'अपना व्यक्तिगत शिक्षण रोडमैप तैयार करें',
    'finder.roadmapBannerDesc': '{skill} से लक्षित कमी वाले व्यवसायों के लिए चरण-दर-चरण ब्रिज कौशल देखें।',
    'finder.viewRoadmap': 'मेरा रोडमैप देखें',

    // My Roadmap Page
    'roadmap.back': 'कौशल खोजक पर वापस जाएं',
    'roadmap.title': 'मेरा शिक्षण रोडमैप',
    'roadmap.subtitle': '{skill} से लक्षित कमी वाले व्यवसाय तक का मार्ग',
    'roadmap.step1Title': 'वर्तमान कौशल आधार रेखा',
    'roadmap.step1Desc': '{skill} में प्रदर्शित योग्यता। (शिक्षा: {education})',
    'roadmap.step1Status': 'वर्तमान',
    'roadmap.step2Title': 'पहचाना गया कौशल अंतराल',
    'roadmap.step2Desc': 'स्तर 5 स्वचालन भूमिकाओं के लिए आवश्यक औद्योगिक नियंत्रक और PLC लैडर लॉजिक मॉड्यूल अनुपस्थित।',
    'roadmap.step2Status': 'अंतराल',
    'roadmap.step3Title': 'अनुशंसित ब्रिज कौशल',
    'roadmap.step3Desc': 'PLC प्रोग्रामिंग और औद्योगिक टेलीमेट्री (6 सप्ताह / 180 घंटे का संरचित प्रशिक्षण)।',
    'roadmap.step3Status': 'ब्रिज',
    'roadmap.step4Title': 'लक्षित योग्यता लक्ष्य',
    'roadmap.step4Desc': 'औद्योगिक स्वचालन तकनीशियन (NCO 2015 कोड: 3115.0100 · उच्च उद्योग कमी)।',
    'roadmap.step4Status': 'लक्षित',
    'roadmap.trainingCentresTitle': 'यह ब्रिज कार्यक्रम संचालित करने वाले प्रशिक्षण केंद्र',
    'roadmap.trainingCentresDesc': 'PMKVY और राज्य कौशल मिशन योजनाओं के तहत रियायती ब्रिज पाठ्यक्रम प्रदान करने वाले मान्यता प्राप्त सरकारी और सहायता प्राप्त ITI।',
    'roadmap.searchAnother': 'अन्य कौशल खोजें',

    // Search Modal
    'search.placeholder': 'NCO कोड (उदा. 1111.0100), कौशल, व्यवसाय, ज़िला खोजें...',
    'search.quickTitle': 'डेटाबेस में त्वरित खोज',
    'search.quickSub': 'NCO 2015 कोड, व्यवसाय का नाम, कौशल कीवर्ड, या ज़िला टाइप करें',
    'search.noResults': '"{query}" के लिए कोई मेल खाता व्यवसाय, कौशल या ज़िला नहीं मिला।',
    'search.occupations': 'व्यवसाय (NCO 2015)',
    'search.skills': 'कौशल',
    'search.districts': 'भौगोलिक ज़िले',
    'search.sectors': 'क्षेत्र',
    'search.filterDashboard': 'डैशबोर्ड फ़िल्टर करें',
    'search.filterSector': 'क्षेत्र फ़िल्टर करें',

    // Map & Geography
    'map.title': 'अखिल भारतीय श्रम बाज़ार मानचित्र',
    'map.instruction': 'ज़िला स्तरीय आसूचना देखने के लिए मानचित्र पर किसी भी राज्य पर क्लिक करें।',
    'map.resetAllIndia': 'अखिल भारतीय पर रीसेट करें',
    'map.loadingStates': 'भारत की स्थानिक सीमाएं लोड हो रही हैं...',
    'map.loadingDistricts': 'ज़िला सीमाएं लोड हो रही हैं...',
    'map.legendTitle': 'श्रम बाज़ार स्थिति',
    'map.statusCriticalShortage': 'गंभीर कमी',
    'map.statusShortage': 'कमी',
    'map.statusBalanced': 'संतुलित',
    'map.statusOversupply': 'अधिशेष',
    'map.statusCriticalOversupply': 'गंभीर अधिशेष',
    'map.statusInsufficient': 'अपर्याप्त डेटा',
    'map.demandLevel': 'मांग स्तर',
    'map.criticalShortages': 'गंभीर कमियां',
    'map.totalPostings': 'कुल विज्ञापन',
    'map.activeEmployers': 'सक्रिय नियोक्ता',
    'map.topShortage': 'शीर्ष कमी',
    'map.clickExplore': 'राज्य का विवरण देखने के लिए क्लिक करें',
    'map.attribution': 'भौगोलिक सीमाएं: DataMeet India स्थानिक डेटाबेस',

    // Common & Badges
    'common.source': 'स्रोत',
    'common.data': 'डेटा',
    'common.provenance': 'डेटा प्रमाण',
    'common.refOfficial': 'आधिकारिक संदर्भ',
    'common.syntheticDev': 'सिंथेटिक / विकास डेटा',
    'common.modeledForecast': 'मॉडल किया गया / पूर्वानुमान',
    'common.observed': 'निरीक्षित',
    'common.loading': 'श्रम आसूचना लोड हो रही है...',
    'common.noData': 'वर्तमान फ़िल्टर से मेल खाता कोई रिकॉर्ड नहीं मिला।',
    'common.close': 'बंद करें',
    'common.high': 'उच्च',
    'common.medium': 'मध्यम',
    'common.low': 'निम्न',
    'common.balanced': 'संतुलित',
    'common.shortage': 'कमी',
    'common.oversupply': 'अधिशेष'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('kushal_lmi_lang');
      if (saved === 'HI' || saved === 'EN') return saved;
    }
    return 'EN';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('kushal_lmi_lang', newLang);
      document.documentElement.lang = newLang === 'HI' ? 'hi' : 'en';
    }
  };

  const toggleLang = () => {
    setLang(lang === 'EN' ? 'HI' : 'EN');
  };

  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.documentElement.lang = lang === 'HI' ? 'hi' : 'en';
    }
  }, [lang]);

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[lang] || translations.EN;
    if (langDict[key]) return langDict[key];
    if (translations.EN[key]) return translations.EN[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
